version: '3'
services:
  webserver:
    build: .
    tty: true
    volumes:
      - ./node/app:/app
    ports:
      - "8080:3000"
    # command: "npx nodemon server.js"
    command: "npx webpack-dev-server --hot"
